### ISSUE TITLE
Unable to load the saved model

### ISSUE THREAD

**Issue by shubhamc-iiitd** [Wangys-prog/prPred-DRLF#1]
Dear Developer,
I am getting an error while unpickling your saved model. Please reupload your model as it appears your model file is corrupted.

`Traceback (most recent call last):
  File "prPred-DRLF.py", line 36, in <module>
    predict(inputfasta,outfile)
  File "prPred-DRLF.py", line 8, in predict
    feature_sel= GnerateFeatures(seq_dict)
  File "get_feature.py", line 22, in GnerateFeatures
  File "./prediction/src/SSA_embedding.py", line 155, in BiLSTM_Embed
    lm_embed, lstm_stack, proj = load_model("./prediction/embbed_models/SSA_embed.model", use_cuda=True)
  File "./prediction/src/SSA_embedding.py", line 98, in load_model
    encoder = torch.load(path)
  File "/home/shubham/.conda/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/shubham/.conda/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`

**Comment by Wangys-prog** [comment]
I tried it, and the code worked
![微信图片_20240411151027](https://github.com/Wangys-prog/prPred-DRLF/assets/53590499/1253ff81-5533-4282-8cdc-da056015c299)

**Comment by shubhamc-iiitd** [comment]
Could you share the pip package versions and the conda environment configuration for better resolution?

**Comment by psgahlot11** [comment]
Dear Developer 
i am getting this issue with running the tool prpred-DRLF can you share all required versions of other packages compatible to run?  your provided version for the tool not working properly.
BiLSTM Embedding...
Traceback (most recent call last):
  File "prPred-DRLF.py", line 36, in <module>
    predict(inputfasta,outfile)
  File "prPred-DRLF.py", line 8, in predict
    feature_sel= GnerateFeatures(seq_dict)
  File "get_feature.py", line 22, in GnerateFeatures
  File "./prediction/src/SSA_embedding.py", line 114, in BiLSTM_Embed
    lm_embed, lstm_stack, proj = load_model("./prediction/embbed_models/SSA_embed.model", use_cuda=True)
  File "./prediction/src/SSA_embedding.py", line 96, in load_model
    encoder = torch.load(path)
  File "/home/pushpendra/anaconda3/envs/Effector-GAN/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/pushpendra/anaconda3/envs/Effector-GAN/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

**Comment by shubhamc-iiitd** [comment]
It seems the error arises because the file isn’t properly uploaded via git-lfs. Kindly recheck.

**Comment by Wangys-prog** [comment]
[cid:8ef002fa-6ccc-4371-abd3-d805dff7534f]SSA_embed.model<https://1drv.ms/u/c/90177c9d5da6d372/EchdC5MHN7xPldbRWCwDSfwBuW4n-JUBIGZqF5ypBZHDtw>

I updated the new version yesterday, and I have tried to run it without error. If you still have errors, please use the attached model to replace it
________________________________
发件人: psgahlot11 ***@***.***>
发送时间: 2024年4月11日 19:12
收件人: Wangys-prog/prPred-DRLF ***@***.***>
抄送: Wangys-prog ***@***.***>; Comment ***@***.***>
主题: Re: [Wangys-prog/prPred-DRLF] Unable to load the saved model (Issue #1)


Dear Developer
i am getting this issue with running the tool prpred-DRLF can you share all required versions of other packages compatible to run? your provided version for the tool not working properly.
BiLSTM Embedding...
Traceback (most recent call last):
File "prPred-DRLF.py", line 36, in
predict(inputfasta,outfile)
File "prPred-DRLF.py", line 8, in predict
feature_sel= GnerateFeatures(seq_dict)
File "get_feature.py", line 22, in GnerateFeatures
File "./prediction/src/SSA_embedding.py", line 114, in BiLSTM_Embed
lm_embed, lstm_stack, proj = load_model("./prediction/embbed_models/SSA_embed.model", use_cuda=True)
File "./prediction/src/SSA_embedding.py", line 96, in load_model
encoder = torch.load(path)
File "/home/pushpendra/anaconda3/envs/Effector-GAN/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/home/pushpendra/anaconda3/envs/Effector-GAN/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

―

**Comment by shubhamc-iiitd** [comment]
The model you provided solved the issue. There is some issue in the GitHub version as it was of a smaller size. Thanks for the assistance!
